require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - db/**/**
    - features/support/env.rb
    - config/**/**
    - test/**/**
    - bin/**/**
    - node_modules/**/**
Layout/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 200
Metrics/MethodLength:
  Enabled: false
Style/BlockComments:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
    - spec/features/user_sees_only_one_category_spec.rb
    - spec/features/user_sees_only_one_category_and_one_brand_spec.rb
RSpec/MultipleMemoizedHelpers:
  Max: 7
Metrics/BlockLength:
  IgnoredMethods: ['describe']
